on:
  push:
    branches: [main]
  pull_request:

steps:
  - uses: actions/checkout@v3

  - name: Setup Python
    uses: actions/setup-python@v2
    with:
      python-version: 3.10

  - name: Install Poetry
    uses: snok/install-poetry@v1
    with:
      version: 1.2.2
      virtualenvs-create: true
      virtualenvs-in-project: true

  - name: Cache the virtualenv
    uses: actions/cache@v2
    with:
      path: ./.venv
      key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

  - name: Install dependencies
    run: |
      python -m poetry install

  - name: Run tests
    run: |
      python -m poetry run python -m pytest -sxv

  - name: Run pre-commit
    uses: pre-commit/action@v3.0.0
